console.log("rodando o sistema de gerenciamento de jogos")
console.log("aplicação está se conectando ao banco de dados")
console.log("o paulo fez esse commit sem vc ver a aula!")
console.log ("eu que fiz!")
console.log ("teste")